language: php

sudo: false
install:
  - composer install
script:
  - vendor/bin/phpunit
  
dist: trusty

php:
  - 5.3
    dist: precise
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

notifications:
  email: false
